"""Declarative base and shared column mixins.

Table declarations live here, separate from 'app.domain.*', and the mapping
between the two lives in 'app.infrastructure.database.mappers'. A schema change
is therefore never a domain change, and vice versa.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention: without it, PostgreSQL assigns generated names to
# constraints and indexes, and Alembic's autogenerate cannot reliably drop or
# alter them. Fixing the convention now avoids painful migrations later.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every SPA table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_primary_key() -> Mapped[uuid.UUID]:
    """Primary key column.

    UUIDs rather than bigserial: identifiers are generated by the application so
    that future independent workers can create analysis results without a
    round-trip to the database, and so that an id cannot be used to enumerate
    how many matches a competitor has processed.
    """
    return mapped_column(primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """' 'created_at' ' / ' 'updated_at' ' maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class OrganizationScopedMixin:
    """Marks a table as belonging to exactly one organization.

    Not a mixin that stores the column (each table declares its own foreign key
    with the right ' 'ondelete' ' behaviour); it documents and type-checks the
    expectation that the column exists, so repository code can rely on it.
    """


def jsonb_column(*, nullable: bool = False) -> Mapped[dict[str, object]]:
    """A JSONB column for genuinely schema-less analysis metadata.

    Used deliberately and sparingly — see ' 'docs/architecture/database.md' '.
    The rule: JSONB holds *metadata about* an analysis (model versions,
    calibration parameters, stage diagnostics, report snapshots), never the
    performance metrics themselves, which must stay queryable.
    """
    return mapped_column(JSONB, nullable=nullable, default=dict)
