"""Shared domain primitives."""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import NewType

# Typed identifiers prevent accidentally passing a team id where a match id is
# expected. They are 'NewType's so they remain plain UUIDs at runtime (and map
# directly onto PostgreSQL 'uuid' columns).
OrganizationId = NewType("OrganizationId", uuid.UUID)
UserId = NewType("UserId", uuid.UUID)
TeamId = NewType("TeamId", uuid.UUID)
PlayerId = NewType("PlayerId", uuid.UUID)
MatchId = NewType("MatchId", uuid.UUID)
VideoId = NewType("VideoId", uuid.UUID)
AnalysisRunId = NewType("AnalysisRunId", uuid.UUID)
TrackingDatasetId = NewType("TrackingDatasetId", uuid.UUID)
TrackObservationId = NewType("TrackObservationId", uuid.UUID)
TrackMetricId = NewType("TrackMetricId", uuid.UUID)
ReportId = NewType("ReportId", uuid.UUID)
JobId = NewType("JobId", uuid.UUID)


def new_id() -> uuid.UUID:
    """Generate a new identifier.

    UUIDv4 rather than a database sequence: identifiers can be generated by the
    application *and* by future independent workers without coordination, which
    matters once analysis runs are produced outside the API process.
    """
    return uuid.uuid4()


def utcnow() -> datetime:
    """Return the current timezone-aware UTC timestamp.

    Always timezone-aware: analysis results from different workers must be
    comparable without guessing a timezone.
    """
    return datetime.now(UTC)


_SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


@dataclass(frozen=True, slots=True)
class Slug:
    """A URL-safe, human-readable identifier (e.g. ' 'acme-fc' ').

    A shared value object because organizations, teams and players all need one
    and the validation rule must not drift between them.
    """

    value: str

    MIN_LENGTH = 2
    MAX_LENGTH = 80

    def __post_init__(self) -> None:
        if not (self.MIN_LENGTH <= len(self.value) <= self.MAX_LENGTH):
            raise ValueError(
                f"Slug must be between {self.MIN_LENGTH} and {self.MAX_LENGTH} characters."
            )
        if not _SLUG_RE.match(self.value):
            raise ValueError("Slug must be lowercase alphanumeric with single hyphens.")

    def __str__(self) -> str:
        return self.value


@dataclass(frozen=True, slots=True)
class VideoSpec:
    """Technical characteristics of an ingested video.

    Describes the *source* material, not the analysis. Stored alongside the
    video record so that processing parameters (frame rate, resolution) can be
    reproduced later.
    """

    duration_seconds: float | None = None
    frame_rate: float | None = None
    width: int | None = None
    height: int | None = None
    codec: str | None = None

    def __post_init__(self) -> None:
        if self.duration_seconds is not None and self.duration_seconds < 0:
            raise ValueError("duration_seconds cannot be negative.")
        if self.frame_rate is not None and self.frame_rate <= 0:
            raise ValueError("frame_rate must be positive.")


@dataclass(frozen=True, slots=True)
class PitchCoordinate:
    """A position on the field of play in normalised pitch space.

    ' 'x' '/' 'y' ' are expressed in metres relative to a canonical pitch, not in
    image pixels. Pixels are meaningless without the camera calibration, which
    differs per video; metres are directly comparable across matches. Mapping
    pixels to pitch space is an ML concern that lives in ' 'ml/' '.
    """

    x: float
    y: float
    z: float = 0.0


@dataclass(frozen=True, slots=True)
class Percentage:
    """A 0-100 value, used for workload/intensity shares and possession."""

    value: float

    def __post_init__(self) -> None:
        if not (0.0 <= self.value <= 100.0):
            raise ValueError("Percentage must be between 0 and 100.")


@dataclass(frozen=True, slots=True)
class MetricValue:
    """A single named performance measurement.

    ' 'unit' ' and ' 'definition_version' ' travel with the number: a metric is
    only interpretable together with how it was computed. This is what makes it
    safe to compare metrics produced by different analysis pipeline versions.
    """

    name: str
    value: float
    unit: str = ""
    definition_version: str = "v1"

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise ValueError("Metric name must not be empty.")


@dataclass(slots=True)
class TimeRange:
    """An interval within a video, in seconds from the start of the recording."""

    start_seconds: float
    end_seconds: float
    _: dict[str, object] = field(default_factory=dict, repr=False)

    def __post_init__(self) -> None:
        if self.start_seconds < 0:
            raise ValueError("start_seconds cannot be negative.")
        if self.end_seconds <= self.start_seconds:
            raise ValueError("end_seconds must be greater than start_seconds.")

    @property
    def duration_seconds(self) -> float:
        return self.end_seconds - self.start_seconds

    def contains(self, seconds: float) -> bool:
        return self.start_seconds <= seconds <= self.end_seconds


@dataclass(frozen=True, slots=True)
class Page:
    """Pagination window for collection endpoints."""

    limit: int = 50
    offset: int = 0

    MAX_LIMIT = 200

    def __post_init__(self) -> None:
        if self.limit < 1 or self.limit > self.MAX_LIMIT:
            raise ValueError(f"limit must be between 1 and {self.MAX_LIMIT}.")
        if self.offset < 0:
            raise ValueError("offset cannot be negative.")
