"""Platform administration: identity, roles, privileges, invitations and MFA.

Seeds the role and privilege catalogues as part of the schema change. They are
reference data the application reads by name, so leaving them to a separate
runtime step would let a deployment come up with roles that grant nothing.
"""

from __future__ import annotations

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c0d52218720"
down_revision: str | None = "e639aa23a560"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_privileges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_privileges")),
        sa.UniqueConstraint("name", name=op.f("uq_admin_privileges_name")),
    )
    op.create_table(
        "admin_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_admin_roles_name")),
    )
    op.create_table(
        "admin_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("invited_by", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_admin_invitations_invited_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["admin_roles.id"],
            name=op.f("fk_admin_invitations_role_id_admin_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_invitations")),
    )
    op.create_index(
        op.f("ix_admin_invitations_email"), "admin_invitations", ["email"], unique=False
    )
    op.create_index(
        "ix_admin_invitations_email_created",
        "admin_invitations",
        ["email", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_admin_invitations_token_hash", "admin_invitations", ["token_hash"], unique=True
    )
    op.create_table(
        "admin_role_privileges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("privilege_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["privilege_id"],
            ["admin_privileges.id"],
            name=op.f("fk_admin_role_privileges_privilege_id_admin_privileges"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["admin_roles.id"],
            name=op.f("fk_admin_role_privileges_role_id_admin_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_role_privileges")),
        sa.UniqueConstraint("role_id", "privilege_id", name="uq_admin_role_privileges_pair"),
    )
    op.create_index(
        op.f("ix_admin_role_privileges_privilege_id"),
        "admin_role_privileges",
        ["privilege_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_role_privileges_role_id"), "admin_role_privileges", ["role_id"], unique=False
    )
    op.create_table(
        "platform_admins",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mfa_enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('invited', 'active', 'suspended', 'revoked')",
            name=op.f("ck_platform_admins_platform_admin_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_platform_admins_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_platform_admins")),
        sa.UniqueConstraint("user_id", name="uq_platform_admins_user_id"),
    )
    op.create_index(
        op.f("ix_platform_admins_user_id"), "platform_admins", ["user_id"], unique=False
    )
    op.create_table(
        "admin_mfa_challenges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("satisfied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["platform_admins.id"],
            name=op.f("fk_admin_mfa_challenges_admin_id_platform_admins"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_admin_mfa_challenges_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_mfa_challenges")),
    )
    op.create_index(
        "ix_admin_mfa_challenges_admin", "admin_mfa_challenges", ["admin_id"], unique=False
    )
    op.create_index(
        "ix_admin_mfa_challenges_session", "admin_mfa_challenges", ["session_id"], unique=False
    )
    op.create_table(
        "admin_mfa_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("secret_encrypted", sa.String(length=512), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["platform_admins.id"],
            name=op.f("fk_admin_mfa_credentials_admin_id_platform_admins"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_mfa_credentials")),
        sa.UniqueConstraint("admin_id", name="uq_admin_mfa_credentials_admin_id"),
    )
    op.create_index(
        op.f("ix_admin_mfa_credentials_admin_id"),
        "admin_mfa_credentials",
        ["admin_id"],
        unique=False,
    )
    op.create_table(
        "admin_privilege_grants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("privilege_id", sa.Uuid(), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["platform_admins.id"],
            name=op.f("fk_admin_privilege_grants_admin_id_platform_admins"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
            name=op.f("fk_admin_privilege_grants_granted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["privilege_id"],
            ["admin_privileges.id"],
            name=op.f("fk_admin_privilege_grants_privilege_id_admin_privileges"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_privilege_grants")),
        sa.UniqueConstraint("admin_id", "privilege_id", name="uq_admin_privilege_grants_pair"),
    )
    op.create_index(
        op.f("ix_admin_privilege_grants_admin_id"),
        "admin_privilege_grants",
        ["admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_privilege_grants_privilege_id"),
        "admin_privilege_grants",
        ["privilege_id"],
        unique=False,
    )
    op.create_table(
        "admin_recovery_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=128), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["platform_admins.id"],
            name=op.f("fk_admin_recovery_codes_admin_id_platform_admins"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_recovery_codes")),
    )
    op.create_index(
        "ix_admin_recovery_codes_admin", "admin_recovery_codes", ["admin_id"], unique=False
    )
    op.create_table(
        "admin_role_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("admin_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["platform_admins.id"],
            name=op.f("fk_admin_role_assignments_admin_id_platform_admins"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name=op.f("fk_admin_role_assignments_assigned_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["admin_roles.id"],
            name=op.f("fk_admin_role_assignments_role_id_admin_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_role_assignments")),
        sa.UniqueConstraint("admin_id", "role_id", name="uq_admin_role_assignments_pair"),
    )
    op.create_index(
        op.f("ix_admin_role_assignments_admin_id"),
        "admin_role_assignments",
        ["admin_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_role_assignments_role_id"),
        "admin_role_assignments",
        ["role_id"],
        unique=False,
    )
    _seed_catalogue()
    # ### end Alembic commands ###


def _seed_catalogue() -> None:
    """Populate the role and privilege catalogues.

    Read from the application's catalogue rather than duplicated here, so the rows
    a deployment seeds are exactly the privileges the application checks for.
    """
    from app.domain.admin.catalogue import (
        PRIVILEGE_DESCRIPTIONS,
        ROLE_DESCRIPTIONS,
        ROLE_PRIVILEGES,
    )

    connection = op.get_bind()

    privilege_ids: dict[str, uuid.UUID] = {}
    for name, description in PRIVILEGE_DESCRIPTIONS.items():
        privilege_id = uuid.uuid4()
        privilege_ids[name] = privilege_id
        connection.execute(
            sa.text(
                "INSERT INTO admin_privileges (id, name, description, created_at, updated_at) "
                "VALUES (:id, :name, :description, now(), now())"
            ),
            {"id": privilege_id, "name": name, "description": description},
        )

    for role_name, description in ROLE_DESCRIPTIONS.items():
        role_id = uuid.uuid4()
        connection.execute(
            sa.text(
                "INSERT INTO admin_roles (id, name, description, created_at, updated_at) "
                "VALUES (:id, :name, :description, now(), now())"
            ),
            {"id": role_id, "name": role_name, "description": description},
        )
        for privilege_name in ROLE_PRIVILEGES[role_name]:
            connection.execute(
                sa.text(
                    "INSERT INTO admin_role_privileges (id, role_id, privilege_id) "
                    "VALUES (:id, :role_id, :privilege_id)"
                ),
                {
                    "id": uuid.uuid4(),
                    "role_id": role_id,
                    "privilege_id": privilege_ids[privilege_name],
                },
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_admin_role_assignments_role_id"), table_name="admin_role_assignments")
    op.drop_index(op.f("ix_admin_role_assignments_admin_id"), table_name="admin_role_assignments")
    op.drop_table("admin_role_assignments")
    op.drop_index("ix_admin_recovery_codes_admin", table_name="admin_recovery_codes")
    op.drop_table("admin_recovery_codes")
    op.drop_index(
        op.f("ix_admin_privilege_grants_privilege_id"), table_name="admin_privilege_grants"
    )
    op.drop_index(op.f("ix_admin_privilege_grants_admin_id"), table_name="admin_privilege_grants")
    op.drop_table("admin_privilege_grants")
    op.drop_index(op.f("ix_admin_mfa_credentials_admin_id"), table_name="admin_mfa_credentials")
    op.drop_table("admin_mfa_credentials")
    op.drop_index("ix_admin_mfa_challenges_session", table_name="admin_mfa_challenges")
    op.drop_index("ix_admin_mfa_challenges_admin", table_name="admin_mfa_challenges")
    op.drop_table("admin_mfa_challenges")
    op.drop_index(op.f("ix_platform_admins_user_id"), table_name="platform_admins")
    op.drop_table("platform_admins")
    op.drop_index(op.f("ix_admin_role_privileges_role_id"), table_name="admin_role_privileges")
    op.drop_index(op.f("ix_admin_role_privileges_privilege_id"), table_name="admin_role_privileges")
    op.drop_table("admin_role_privileges")
    op.drop_index("ix_admin_invitations_token_hash", table_name="admin_invitations")
    op.drop_index("ix_admin_invitations_email_created", table_name="admin_invitations")
    op.drop_index(op.f("ix_admin_invitations_email"), table_name="admin_invitations")
    op.drop_table("admin_invitations")
    op.drop_table("admin_roles")
    op.drop_table("admin_privileges")
    # ### end Alembic commands ###
