"""Add processing_jobs — the durable record of asynchronous video work.

Hand-written rather than autogenerated so the constraint and index names match
the model exactly: CI compares the migrated schema against 'Base.metadata' and
fails on any drift.

Revision ID: 20260926_0002
Revises: 20250925_0001
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260926_0002"
down_revision: str | None = "20250925_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 0", name="ck_processing_jobs_attempt_non_negative"),
        sa.CheckConstraint(
            "max_attempts >= 1", name="ck_processing_jobs_max_attempts_positive"
        ),
        sa.CheckConstraint(
            "progress >= 0 AND progress <= 100",
            name="ck_processing_jobs_job_progress_within_range",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="fk_processing_jobs_organization_id_organizations",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name="fk_processing_jobs_video_id_videos",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_processing_jobs"),
    )
    op.create_index("ix_processing_jobs_organization_id", "processing_jobs", ["organization_id"])
    op.create_index("ix_processing_jobs_video_id", "processing_jobs", ["video_id"])
    op.create_index(
        "ix_processing_jobs_video_type_status",
        "processing_jobs",
        ["video_id", "job_type", "status"],
    )
    op.create_index(
        "ix_processing_jobs_org_status",
        "processing_jobs",
        ["organization_id", "status"],
    )


def downgrade() -> None:
    op.drop_table("processing_jobs")
